# Generated by Django 3.2 on 2022-06-18 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220618_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date'], 'verbose_name': 'my posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
