# Generated by Django 3.2 on 2022-06-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220618_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'my posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
    ]
